---
- name: Install Nagios on Ubuntu
  apt:
    name: 
      - nagios3
      - nagios-nrpe-plugin
      - nagios-plugins
    state: present
    update_cache: yes

- name: Start and enable Nagios on Ubuntu
  systemd:
    name: nagios3
    state: started
    enabled: yes

