---
- hosts: CentOSs, Ubuntus
  become: true
  pre_tasks:

  - name: Update repository Index (CentOS)
    tags: always
    yum:
      name: "*"
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Update repository Index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: Ensured Required packages
    package:
      name:
        - gcc
        - make
        - wget

  - name: Create Nagios User
    user:
      name: nagios1
      shell: /bin/bash
      system: yes
      create_home: yes

  - name: Create nagios group
    group:
      name: nagios_group1
      system: yes

- hosts: Ubuntus
  become: true
  roles:
    -  Ubuntu

- hosts: CentOSs
  become: true
  roles:
    -  CentOS
